filter:
    excluded_paths:
        - '*.min.js'
        - 'boot/*'
        - 'legacy/*'
        - 'loaders/*'
        - 'source/*'
        - 'test/*'
        - 'umd/*'
        - 'directives/froala.js'
        - 'directives/redactor.js'
checks:
    javascript: true
build:
#    dependencies:
#        override:
#            - npm install --only=dev
    nodes:
        analysis:
            tests:
                override:
                    -
                        command: jshint-run
                        use_website_config: false
                    - js-scrutinizer-run
            environment:
                node:
                    version: 8.0.0
        tests: true
