dist: xenial
os: linux
language: nodejs
services:
  - mongodb
  - mysql
  - redis
jobs:
  include:
    - language: node_js
      # EOL: 2021-04-30
      name: "NodeJS 10 LTS: Dubnium"
      node_js:
        - "10"
      cache:
        directories:
          - node_modules
    - language: node_js
      # EOL: 2022-04-30
      name: "NodeJS 12 LTS: Erbium"
      node_js:
        - "12"
      cache:
        directories:
          - node_modules

#    - language: node_js
#      # EOL: 2020-06-01
#      name: "NodeJS 13"
#      node_js:
#        - "13"
#      cache:
#        directories:
#          - node_modules

    - language: node_js
      # EOL: 2023-04-30
      name: "NodeJS 14: Fermium"
      node_js:
        - "14"
      cache:
        directories:
          - node_modules

#    - language: node_js
#      # EOL: 2021-06-01
#      name: "NodeJS 15"
#      node_js:
#        - "15"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: 2024-04-30
#      name: "NodeJS 16: Gallium"
#      node_js:
#        - "16"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: 2022-06-01
#      name: "NodeJS 17"
#      node_js:
#        - "17"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: 2025-04-30
#      name: "NodeJS 18: Hydrogen"
#      node_js:
#        - "18"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: 2023-06-01
#      name: "NodeJS 19"
#      node_js:
#        - "19"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: 2026-04-30
#      name: "NodeJS 20: Iron"
#      node_js:
#        - "20"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: Indeterminate
#      name: "NodeJS: LTS"
#      node_js:
#        - "lts/*"
#      cache:
#        directories:
#          - node_modules

#    - language: node_js
#      # EOL: Indeterminate
#      name: "NodeJS: Stable"
#      node_js:
#        - "node"
#      cache:
#        directories:
#          - node_modules

#      before_install:
#        - export CHROME_BIN=chromium-browser
#        - export DISPLAY=:99.0
#        - sh -e /etc/init.d/xvfb start
#      before_script:
#        - npm install
#      script: node_modules/karma/bin/karma start karma.conf.js --single-run
#addons:
#  firefox: latest
#  sauce_connect:
#    username: "Your Sauce Labs username"
#    access_key: "Your Sauce Labs access key"
#  apt:
#    sources:
#    - google-chrome
#    packages:
#    - google-chrome-stable
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: EsATuqYpNd89o4nTuE1Lr7e84jDM3doWMkk1vZf+TEWexFcWdrEmKXvsqcH2CUelYD/REWDi4hyZU+zurfhoXMOlwmDhEk85KUhX40lfxJrw4FSNAaVjBsxYfCEAxDNIAG6sUDCKw9zj1OZxx1jGu9XofSZquQhRtOvw+YRNMcvFwGtGOpKN2DICnkJrBIH2TYaNwfq9l+yD4FkTL8IykNLEvKjXOjn+/oCEUCwolyvcp3/gxEC4q8UE95e6DbeW4bpAt037//frNGiMlb3F8Av+5Ceu584My2l+D8UScwkDoBau1ZD5scdThz1UUIlLGaAr/GHbGIM7kbsnQ0Vc6l+r6gNgza3+F30S1ufs589o3l8BwUDgMMWASddIittOLEZDW9k4RAPsp/YHU/AQQ3Mfv8ELEeJlXRCyRhvAvOOFzKP9LoyTI046Mihl3ZdJaVghB9dsaVVhiu1egTQCC8L6JCjiU9bM9qH43QOaqbCyeBUMty+Uon9YCcOIq+mFHrdDLuBTNNRBFjRa8VYrQLEbWfZRzg15aF5Ce3jRw9SdtjHN3dHvsedpvGl6Zt6WQVQe0eTBOl9d4xYTkCqJqEUFQj5olIytMDJu5Sr8d9lkGpvGUavGr6oDmFBZVqS+vSzurTBg8GPKiJq33RNZt802FNjmedxPsizo7wz6EcI=
